av/urls.py
# av/urls.py
from django.urls import path

from av import views as av_views

app_name = 'av'

urlpatterns = [
   path('', av_views.AVHome.as_view(), name="index"),
   path('view/<int:id>/', av_views.media_view, name="view"),
   path('view/set-image-default/<int:image_id>',
        av_views.set_default_image_view,
        name="set_default_image"),
   path('upload', av_views.Upload.as_view(), name="upload"),
   path('upload/success/<int:id>/',
        av_views.UploadSuccess.as_view(),
        name="upload_success"),
]

oppia/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import path
from django.views import static
from django.views.generic import TemplateView
from oppia import views as oppia_views


# Custom HTTP response pages
handler403 = 'oppia.permissions.oppia_403_handler'

app_name = 'oppia'
urlpatterns = [

    path('', oppia_views.home_view, name="index"),
    path('server/', oppia_views.server_view, name="server"),
    path('about/', oppia_views.about_view, name="about"),

    path('teacher', oppia_views.teacher_home_view, name="teacher_index"),

    path('leaderboard', oppia_views.leaderboard_view, name="leaderboard"),
    path('upload', oppia_views.upload_step1, name="upload"),
    path('upload2/<int:course_id>',
         oppia_views.upload_step2,
         name="upload_step2"),
    path('upload2/success',
         TemplateView.as_view(template_name="course/upload-success.html"),
         name="upload_success"),
    path('course/',
         oppia_views.courses_list_view,
         name="course"),
    path('course/tag/<int:tag_id>',
         oppia_views.tag_courses_view,
         name="tag_courses"),
    path('course/<int:course_id>/',
         oppia_views.recent_activity,
         name="recent_activity"),
    path('course/<int:course_id>/edit/',
         oppia_views.upload_step2,
         {'editing': True},
         name="course_edit"),
    path('course/<int:course_id>/detail/',
         oppia_views.recent_activity_detail,
         name="recent_activity_detail"),
    path('course/<int:course_id>/detail/export/',
         oppia_views.export_tracker_detail,
         name="export_tracker_detail"),
    path('course/<int:course_id>/download',
         oppia_views.CourseDownload.as_view(),
         name="course_download"),
    path('course/<int:course_id>/structure/',
         oppia_views.CourseStructure.as_view(),
         name="course_structure"),

    path('cohort/',
         oppia_views.cohort_list_view,
         name="cohorts"),
    path('cohort/add/',
         oppia_views.cohort_add,
         name="cohort_add"),
    path('cohort/<int:cohort_id>/edit/',
         oppia_views.cohort_edit,
         name="cohort_edit"),
    path('cohort/<int:cohort_id>/view/',
         oppia_views.cohort_view,
         name="cohort_view"),
    path('cohort/<int:cohort_id>/<int:course_id>/view/',
         oppia_views.cohort_course_view,
         name="cohort_course_view"),
    path('cohort/<int:cohort_id>/leaderboard',
         oppia_views.cohort_leaderboard_view,
         name="cohort_leaderboard"),

    path('view/',
         oppia_views.app_launch_activity_redirect_view,
         name="app_launch_activity_redirect"),
    url(r'^media/(?P<path>.*)$',
        static.serve,
        {'document_root': settings.MEDIA_ROOT}),
]

oppiamobile/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    url(r'^', include('oppia.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^content/', include('content.urls')),
    url(r'^profile/', include('profile.urls')),
    url(r'^reports/', include('reports.urls')),
    url(r'^activitylog/', include('activitylog.urls')),
    url(r'^viz/', include('viz.urls')),
    path(r'av', include('av.urls', namespace="oppia_av")),
    url(r'^gamification/', include('gamification.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^integrations/', include('integrations.urls')),
]

profile/urls.py
from django.contrib.auth import views as django_contrib_auth_views
from django.urls import path
from django.views import i18n as django_views_i18n
from django.views.generic import TemplateView

from profile import views as profile_views

app_name = 'profile'

urlpatterns = [
    path('register/', profile_views.register, name="register"),
    path('register/thanks/',
         TemplateView.as_view(template_name="oppia/thanks.html"),
         name="register_thanks"),
    path('login/', profile_views.login_view, name="login"),
    path('logout/',
         django_contrib_auth_views.LogoutView.as_view(),
         {'template_name': 'oppia/logout.html', },
         name="logout"),
    path('setlang/', django_views_i18n.set_language, name="set_language"),
    path('reset/', profile_views.reset, name="reset"),
    path('reset/sent/',
         TemplateView.as_view(template_name="profile/reset-sent.html"),
         name="reset_sent"),
    path('edit/', profile_views.edit, name="edit"),
    path('edit/<int:user_id>/', profile_views.edit, name="edit_user"),
    path('points/', profile_views.points, name="points"),
    path('badges/', profile_views.badges, name="badges"),
    path('<int:user_id>/activity/',
         profile_views.user_activity,
         name="user_activity"),
    path('<int:user_id>/<int:course_id>/activity/',
         profile_views.user_course_activity_view,
         name="user_course_activity"),

    path('<int:user_id>/quizattempts/',
         profile_views.UserAttemptsList.as_view(),
         name="user_all_attempts"),

    path('<int:user_id>/<int:course_id>/quiz/<int:quiz_id>/attempts/',
         profile_views.QuizAttemptsList.as_view(),
         name="user_quiz_attempts"),

    path('<int:user_id>/<int:course_id>/quiz/<int:quiz_id>/attempts/<int:pk>',
         profile_views.QuizAttemptDetail.as_view(),
         name="quiz_attempt_detail"),

    path('upload/', profile_views.UploadUsers.as_view(), name="upload"),
    path('search/', profile_views.search_users, name="search"),
    path('export/', profile_views.export_users, name="export"),
    path('list/', profile_views.list_users, name="list"),

    path('delete/<int:user_id>/', profile_views.delete_account_view, name="delete"),
    path('delete/complete/',
         profile_views.delete_account_complete_view,
         name="delete_complete"),
    path('export/mydata/<data_type>',
         profile_views.export_mydata_view,
         name="export_mydata"),
]

oppia/forms/cohort.py
import datetime

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div
from django import forms
from django.utils.translation import ugettext_lazy as _


class CohortHelperDiv(Div):
    template = "cohort/helper.html"


class CohortForm(forms.Form):

    STR_VALID_DATE = _(u'Please enter a valid date')
    DATE_FORMAT = "%Y-%m-%d"

    description = forms.CharField(required=True)
    teachers = forms.CharField(
        widget=forms.Textarea(),
        required=False,
        help_text=_("A comma separated list of usernames"))
    students = forms.CharField(
        widget=forms.Textarea(),
        required=False,
        help_text=_("A comma separated list of usernames"))
    start_date = forms.CharField(
        required=True,
        error_messages={'required': STR_VALID_DATE,
                        'invalid': STR_VALID_DATE})
    end_date = forms.CharField(
        required=True,
        error_messages={'required': STR_VALID_DATE,
                        'invalid': STR_VALID_DATE})
    courses = forms.CharField(
        widget=forms.Textarea(),
        required=False,
        help_text=_("A comma separated list of course codes"))

    def __init__(self, *args, **kwargs):
        super(CohortForm, self).__init__(* args, ** kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_tag = False
        self.helper.label_class = 'col-sm-3 col-md-2'
        self.helper.field_class = 'col-sm-9 col-md-10 col-lg-9'
        self.helper.layout = Layout(
                'description',
                Div('start_date', css_class='date-picker-row'),
                Div('end_date', css_class='date-picker-row'),
                Div(
                    'courses',
                    'teachers',
                    'students',
                    css_class='d-none'
                ),
            )

    def clean(self):
        cleaned_data = super(CohortForm, self).clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        DATE_FORMAT = "%Y-%m-%d"
        try:
            start_date = datetime.datetime.strptime(start_date, DATE_FORMAT)
        except (TypeError, ValueError):
            raise forms.ValidationError(_("Please enter a valid start date"))
        try:
            end_date = datetime.datetime.strptime(end_date, DATE_FORMAT)
        except (TypeError, ValueError):
            raise forms.ValidationError(_("Please enter a valid end date"))

        # check start date before end date
        if start_date > end_date:
            raise forms.ValidationError(
                _("Start date must be before the end date."))

        return cleaned_data

oppia/views/activity.py
import datetime
import json

import tablib
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.db.models import Sum
from django.db.models.functions import TruncDay, TruncMonth, TruncYear
from django.http import HttpResponse
from django.shortcuts import render

from helpers.forms.dates import DateRangeIntervalForm, DateRangeForm
from oppia.models import Points
from oppia.models import Tracker
from oppia.permissions import can_view_course_detail
from oppia.views.utils import generate_graph_data
from reports.signals import dashboard_accessed
from summary.models import CourseDailyStats


def recent_activity(request, course_id):

    course = can_view_course_detail(request, course_id)

    dashboard_accessed.send(sender=None, request=request, data=course)

    start_date = datetime.datetime.now() - datetime.timedelta(days=31)
    end_date = datetime.datetime.now()
    interval = 'days'

    if request.method == 'POST':
        form = DateRangeIntervalForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data.get("start_date")
            start_date = datetime.datetime.strptime(start_date + " 00:00:00",
                                                    "%Y-%m-%d %H:%M:%S")
            end_date = form.cleaned_data.get("end_date")
            end_date = datetime.datetime.strptime(end_date + " 23:59:59",
                                                  "%Y-%m-%d %H:%M:%S")
            interval = form.cleaned_data.get("interval")
    else:
        data = {}
        data['start_date'] = start_date
        data['end_date'] = end_date
        data['interval'] = interval
        form = DateRangeIntervalForm(initial=data)

    dates = []
    if interval == 'days':
        daily_stats = CourseDailyStats.objects.filter(course=course,
                                                      day__gte=start_date,
                                                      day__lte=end_date) \
                        .annotate(stat_date=TruncDay('day')) \
                        .values('stat_date', 'type') \
                        .annotate(total=Sum('total'))

        dates = generate_graph_data(daily_stats, False)

    else:
        monthly_stats = CourseDailyStats.objects.filter(course=course,
                                                        day__gte=start_date,
                                                        day__lte=end_date) \
                        .annotate(month=TruncMonth('day'),
                                  year=TruncYear('day')) \
                        .values('month', 'year', 'type') \
                        .annotate(total=Sum('total')) \
                        .order_by('year', 'month')

        dates = generate_graph_data(monthly_stats, True)

    leaderboard = Points.get_leaderboard(10, course)
    return render(request, 'course/activity.html',
                  {'course': course,
                   'monthly': interval == 'months',
                   'form': form,
                   'data': dates,
                   'leaderboard': leaderboard})


def recent_activity_detail(request, course_id):
    course = can_view_course_detail(request, course_id)

    start_date = datetime.datetime.now() - datetime.timedelta(days=31)
    end_date = datetime.datetime.now()
    if request.method == 'POST':
        form = DateRangeForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data.get("start_date")
            start_date = datetime.datetime.strptime(start_date, "%Y-%m-%d")
            end_date = form.cleaned_data.get("end_date")
            end_date = datetime.datetime.strptime(end_date, "%Y-%m-%d")
            trackers = Tracker.objects.filter(course=course,
                                              tracker_date__gte=start_date,
                                              tracker_date__lte=end_date) \
                              .order_by('-tracker_date')
        else:
            trackers = Tracker.objects.filter(course=course) \
                .order_by('-tracker_date')
    else:
        data = {}
        data['start_date'] = start_date
        data['end_date'] = end_date
        form = DateRangeForm(initial=data)
        trackers = Tracker.objects.filter(course=course) \
            .order_by('-tracker_date')

    paginator = Paginator(trackers, 25)
    # Make sure page request is an int. If not, deliver first page.
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    # If page request (9999) is out of range, deliver last page of results.
    try:
        tracks = paginator.page(page)
        for t in tracks:
            t.data_obj = []
            try:
                data_dict = json.loads(t.data)
                for key, value in data_dict.items():
                    t.data_obj.append([key, value])
            except ValueError:
                pass
            t.data_obj.append(['agent', t.agent])
            t.data_obj.append(['ip', t.ip])
    except (EmptyPage, InvalidPage):
        tracks = paginator.page(paginator.num_pages)

    return render(request, 'course/activity-detail.html',
                  {'course': course,
                   'form': form,
                   'page': tracks, })


def export_tracker_detail(request, course_id):
    course = can_view_course_detail(request, course_id)

    headers = ('Date',
               'UserId',
               'Type',
               'Activity Title',
               'Section Title',
               'Time Taken',
               'IP Address',
               'User Agent',
               'Language')
    data = []
    data = tablib.Dataset(* data, headers=headers)
    trackers = Tracker.objects.filter(course=course).order_by('-tracker_date')
    for t in trackers:
        try:
            data_dict = json.loads(t.data)
            if 'lang' in data_dict:
                lang = data_dict['lang']
            else:
                lang = ""
            data.append((t.tracker_date.strftime('%Y-%m-%d %H:%M:%S'),
                         t.user.id,
                         t.type,
                         t.get_activity_title(),
                         t.get_section_title(),
                         t.time_taken,
                         t.ip,
                         t.agent,
                         lang))
        except ValueError:
            data.append((t.tracker_date.strftime('%Y-%m-%d %H:%M:%S'),
                         t.user.id,
                         t.type,
                         "",
                         "",
                         t.time_taken,
                         t.ip,
                         t.agent,
                         ""))

    response = HttpResponse(
        data.export('xlsx'),
        content_type='application/vnd.ms-excel;charset=utf-8')
    response['Content-Disposition'] = "attachment; filename=export.xlsx"

    return response

oppia/views/utils.py
import datetime
from django.core.paginator import Paginator

from oppia.models import Course


def get_paginated_courses(request):
    default_order = 'lastupdated_date'
    ordering = request.GET.get('order_by', None)
    if ordering is None:
        ordering = default_order

    courses = Course.objects.all().order_by(ordering)
    paginator = Paginator(courses, 5)

    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    return ordering, paginator.page(page)


def generate_graph_data(dates_types_stats, is_monthly=False):
    dates = []

    current_date = None
    current_stats = {}

    for date in dates_types_stats:
        if is_monthly:
            # depending if it is monthly or daily, we parse differently the
            # day "tag"
            day = date['month']
        else:
            day = date['stat_date']

        if current_date is None or day != current_date:
            if current_date is not None:
                dates.append([current_date, current_stats])
            current_date = day
            current_stats = {'page': 0,
                             'quiz': 0,
                             'media': 0,
                             'resource': 0,
                             'total': 0}

        current_stats[date['type']] = date['total']
        current_stats['total'] += date['total']

    if current_date is not None:
        dates.append([current_date, current_stats])

    return dates

templates/oppia/about.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load settings_value %}
{% block extra_head_title %}
	{% trans 'About' %}
{% endblock extra_head_title %}

{% block header %}
<div class="jumbotron mb-4">
	<h3>{% trans 'About' %}</h3>
</div>
{% endblock header %}


{% block content %}

{% settings_value 'OPPIA_ANDROID_PACKAGEID' as package_id %}
{% blocktrans %}
	<p><a href="https://digital-campus.org/oppiamobile/">Learn-Renewables
	</a> is the mobile learning platform from <a href="https://digital-campus.org">
	Renewables-Liberia and Renewables-Salone</a> to deliver learning content, multimedia and quizzes on
	your smartphone. All the content and activities can	be accessed and used
	even when you don't have an internet connection available on your mobile.</p>
	<p>To get started with our courses, <a href="https://play.google.com/store/apps/details?id={{package_id}}">download the Learn-Renewables app</a>.
{% endblocktrans %}

<h3>{% trans 'Partners' %}</h3>
{% static "oppia/images/UAHlogo.jpg" as uah_logo%}
{% static "oppia/images/LMH-logo.png" as lmh_logo%}
{% static "oppia/images/CHA-logo.png" as cha_logo%}

{% blocktrans %}
	<p>The development of Learn-Renewables is made possible with the support and
collaboration of our partners:</p>
	<a href="https://uah.es/"><img src="{{ uah_logo }}" alt="UAH logo" style="margin:20px"/></a>	
	<a href="https://lastmilehealth.org/"><img src="{{ lmh_logo }}" alt="Last Mile Health logo" style="margin:20px"/></a>
	<a href="https://lastmilehealth.org/chacademy/"><img src="{{ cha_logo }}" alt="Community Health Academy logo" style="margin:20px"/></a>
{% endblocktrans %}

<h3>{% trans 'Previous Funders' %}</h3>
{% static "oppia/images/ukaid.png" as ukaid_logo %}
{% static "oppia/images/mPoweringlogo.jpg" as mpowering_logo %}
{% static "oppia/images/aecid-logo.png" as aecid_logo %}

{% blocktrans %}
	<a href="https://dfid.gov.uk/"><img src="{{ ukaid_logo }}" alt="UK AID logo" style="margin:20px"/></a>	
	<a href="http://www.aecid.es/"><img src="{{ aecid_logo }}" alt="AECID logo" style="margin:20px"/></a>
	<a href="https://mpoweringhealth.org/"><img src="{{ mpowering_logo }}" alt="mPowering logo" style="margin:20px"/></a>
{% endblocktrans %}

<h3>{% trans 'Contributors' %}</h3>
{% blocktrans %} 	
	<p>Acknowledgements and contributors to the code include:</p>
		<ul>
		<li>Safdar Ali & Durba Gogia - Hindi translation</li>
		<li>Roman Blanco - Spanish translation</li>
		<li>Marijs Carrin - for testing and development</li>
		<li><a href="https://github.com/jjoseba">Joseba</a> - technical development, performance improvements and bug fixes</li>
		<li>Adrián Domínguez - technical development, performance improvements and bug fixes</li>
		<li><a href="https://github.com/jbc25">Julio Berzal</a> - technical development, performance 
  improvements and bug fixes</li>
		<li>Laila Hussain - Urdu translation</li>
		<li><a href="http://lal.ngo">Lebanese Alternative Learning</a> - Arabic (Lebanese) translation and funding for drag and drop quizzes</li>
		<li><a href="http://lastmilehealth.org">Last Mile Health</a> - Funding for additional development</li>
		<li>David Gil de Gómez Pérez - technical development, performance improvements and bug fixes</li>
		<li><a href="https://github.com/lexm/">Lex Myers</a></li>
		<li><a href="https://github.com/hakimks">Kawesi Hakim</a></li>
		<li><a href="https://github.com/Ziirofans">Ziirofan</a></li>
	</ul>
	
{% endblocktrans %}

<h3>{% trans 'Code Libraries' %}</h3>
{% blocktrans %} 
	<ul>
		<li><a href="http://getbootstrap.com/">Bootstrap</a></li>
		<li><a href="http://www.brightec.co.uk/blog/custom-android-media-controller">Brightec</a> - video controller</li>
		<li><a href="http://androidplot.com/">AndroidPlot</a> - for graphing library</li>
		<li><a href="http://square.github.io/okhttp/">OkHttp</a> - HTTP library</li>
		<li><a href="https://github.com/square/picasso">Picasso (by SquareUp)</a> - image caching library</li>
	</ul>
{% endblocktrans %}

<a id="terms"></a>
<h3>{% trans 'Terms and License' %}</h3>
{% blocktrans with settings.SERVER_EMAIL as email %}
<p>Learn-Renewables is a work in progress and is provided as-is. Not everything may work 100%, so if you find anything wrong, then <a href="https://community.oppia-mobile.org/">please let us know</a>.</p>

<h3>License</h3>
<p>Learn-Renewables is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.</p>

<p>Learn-Renewables is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.</p>

<p>You should have received a copy of the GNU General Public License
along with Learn-Renewables.  If not, see <a href="http://www.gnu.org/licenses/">http://www.gnu.org/licenses/</a>.</p>

{% endblocktrans %}

{% endblock %}

templates/oppia/home-teacher.html
{% extends "base.html" %}
{% load i18n %}
{% load display_functions %}

{% block extra_head_title %}
	{% trans 'Home' %}
{% endblock extra_head_title %}

{% block content %}

<h3>{% trans 'Recent Activity' %}</h3>
{% include "oppia/includes/activity-graph.html" %}	

<h3>{% trans 'Cohorts' %}</h3>
<div class="table-responsive">
         <table class="table table-striped">
         	<caption class="d-none">{% trans "Cohorts" %}</caption>
         	<thead>
                <tr>
                  <th scope="col">{% trans 'Cohort' %}</th>
                  <th scope="col">{% trans 'No Students' %}</th>
                  <th scope="col">{% trans 'Courses' %}</th>
                </tr>
              </thead>
              <tbody>

				{% for cohort in cohorts %}
					<tr>
						<td><a href="{% url 'oppia:cohort_view' cohort.id %}">{{ cohort.description }}</a></td>
						<td>{{ cohort.no_student_members }}</td>
						<td>
						{% for course in cohort.get_courses %}
							<a href="{% url 'oppia:cohort_course_view' cohort.id course.id %}">{{ course.title|title_lang:LANGUAGE_CODE }}</a><br/>
						{% endfor %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
 		</table>
	</div>

{% endblock %}

templates/oppia/home.html
{% extends "base.html" %}
{% load i18n %}
{% load display_functions %}
{% load settings_value %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_head_title %}
	{% trans 'Home' %}
{% endblock extra_head_title %}

{% block header %}
{% if user.is_authenticated %}
<div class="jumbotron mb-4 ">
	<div class="row">
		<div class="col-md-5"><h3>{% trans 'courses_recent_activity' %}</h3></div>
		<div class="col-md-7">{% include "common/form/date-range.html" with dateform=form %}</div>
	</div>


</div>
{% endif %}
{% endblock header %}

{% block content %}

{% if user.is_authenticated %}
	<div>
		{% include "oppia/includes/activity-graph.html" %}	
	</div>
	{% include "includes/messages.html" %}	

	<h3 class="mt-3">{% trans 'home_leaderboard' %}<a class="btn btn-primary" style="margin-left:20px;" href="{% url 'oppia_gamification_leaderboard_export_server' %}" download="leaderboard.json">{% trans 'Export' %}</a></h3>
	{% include "oppia/includes/leaderboard.html" %}
	<div><a href="{% url 'oppia:leaderboard' %}">{% trans "more..." %}</a></div>
{% else %}
    {% static "oppia/images/lr-logo-150x150.png" as oppia_logo %}

	{% settings_value 'OPPIA_ANDROID_PACKAGEID' as package_id %}
	{% blocktrans %}
	<div style="text-align:center; margin-top:20px;">
		<img src="{{ oppia_logo }}" alt="Learn-Renewables logo"/>
	</div>
	<div style="max-width:350px; text-align:center; margin: 10px auto ">
	<p><a href="https://digital-campus.org/oppiamobile/">Learn-Renewables</a> is the mobile learning platform for topics related to renewable energy from <a href="http://www.renewables-liberia.info">Renewables-Liberia and Renewables-Salone</a> to deliver learning content, multimedia and quizzes on your smartphone. All the content and activities can
	be accessed and used even when you don't have an internet connection available on your mobile.</p>

	<a class="btn-primary btn btn-default" href="https://play.google.com/store/apps/details?id={{package_id}}">Download Learn-Renewables app</a>
	</div>
	{% endblocktrans %}

{% endif %}

{% endblock %}

templates/oppia/leaderboard.html
{% extends "base.html" %}
{% load i18n %}
{% load display_functions %}
{% load static %}

{% block extra_head_title %}
	{% trans 'Leaderboard' %}
{% endblock extra_head_title %}

{% block header %}
<div class="jumbotron mb-4 ">
	<div class="row">
		<div class="col-md-5"><h3><em class="fas fa-trophy mr-2"></em> {% trans 'Leaderboard' %}</h3></div>
		<div class="col-md-7"><a class="btn btn-light" style="margin-left:20px;" href="{% url 'oppia_gamification_leaderboard_export_server' %}" download="leaderboard.json">{% trans 'Export Leaderboard' %}</a></div>
	</div>
</div>
{% endblock header %}

{% block content %}

{% if page.object_list %}
    <div class="table-responsive">
         <table class="table table-striped">
         	 <caption class="d-none">{% trans "Leaderboard" %}</caption>
         	 <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">{% trans 'User' %}</th>
                  <th scope="col">{% trans 'Points' %}</th>
                  <th scope="col">{% trans 'Badges' %}</th>
                </tr>
              </thead>
              <tbody>
				{% include "common/leaderboard-rows.html" %}
	    	</tbody>
 		</table>
	</div>
	{% include "common/pagination.html" %}
{% endif %}
{% endblock %}

templates/oppia/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_head_title %}
	{% trans 'Logged Out' %}
{% endblock extra_head_title %}

{% block content %}
<h2>{% trans 'Logged Out' %}</h2>
{% url 'profile:login' as url_login %}
<p>{% blocktrans %}You are now logged out. <a href="{{ url_login }}">Log in again</a>{% endblocktrans %}</p>
{% endblock %}

templates/oppia/server.html
{% load i18n %}{"version":"{{ version }}",
	"name":"Learn-Renewables",
	"admin_email":"{% blocktrans with settings.SERVER_EMAIL as email %}{{email}}{% endblocktrans %}",
	"max_upload":{{ settings.OPPIA_MAX_UPLOAD_SIZE }}}

templates/oppia/thanks.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h2>{% trans 'page_title_register' %}</h2>
{% url 'oppia:index' as url_home %}
<p>{% blocktrans %}Thanks for registering. You are now logged in. <a href="{{ url_home }}">Return to the homepage</a>{% endblocktrans %}</p>
{% endblock %}