av/urls.py
# av/urls.py
from django.urls import path

from av import views as av_views

app_name = 'av'

urlpatterns = [
   path('', av_views.AVHome.as_view(), name="index"),
   path('view/<int:id>/', av_views.media_view, name="view"),
   path('view/set-image-default/<int:image_id>',
        av_views.set_default_image_view,
        name="set_default_image"),
   path('upload', av_views.Upload.as_view(), name="upload"),
   path('upload/success/<int:id>/',
        av_views.UploadSuccess.as_view(),
        name="upload_success"),
]

oppia/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import path
from django.views import static
from django.views.generic import TemplateView
from oppia import views as oppia_views


# Custom HTTP response pages
handler403 = 'oppia.permissions.oppia_403_handler'

app_name = 'oppia'
urlpatterns = [

    path('', oppia_views.home_view, name="index"),
    path('server/', oppia_views.server_view, name="server"),
    path('about/', oppia_views.about_view, name="about"),

    path('teacher', oppia_views.teacher_home_view, name="teacher_index"),

    path('leaderboard', oppia_views.leaderboard_view, name="leaderboard"),
    path('upload', oppia_views.upload_step1, name="upload"),
    path('upload2/<int:course_id>',
         oppia_views.upload_step2,
         name="upload_step2"),
    path('upload2/success',
         TemplateView.as_view(template_name="course/upload-success.html"),
         name="upload_success"),
    path('course/',
         oppia_views.courses_list_view,
         name="course"),
    path('course/tag/<int:tag_id>',
         oppia_views.tag_courses_view,
         name="tag_courses"),
    path('course/<int:course_id>/',
         oppia_views.recent_activity,
         name="recent_activity"),
    path('course/<int:course_id>/edit/',
         oppia_views.upload_step2,
         {'editing': True},
         name="course_edit"),
    path('course/<int:course_id>/detail/',
         oppia_views.recent_activity_detail,
         name="recent_activity_detail"),
    path('course/<int:course_id>/detail/export/',
         oppia_views.export_tracker_detail,
         name="export_tracker_detail"),
    path('course/<int:course_id>/download',
         oppia_views.CourseDownload.as_view(),
         name="course_download"),
    path('course/<int:course_id>/structure/',
         oppia_views.CourseStructure.as_view(),
         name="course_structure"),

    path('cohort/',
         oppia_views.cohort_list_view,
         name="cohorts"),
    path('cohort/add/',
         oppia_views.cohort_add,
         name="cohort_add"),
    path('cohort/<int:cohort_id>/edit/',
         oppia_views.cohort_edit,
         name="cohort_edit"),
    path('cohort/<int:cohort_id>/view/',
         oppia_views.cohort_view,
         name="cohort_view"),
    path('cohort/<int:cohort_id>/<int:course_id>/view/',
         oppia_views.cohort_course_view,
         name="cohort_course_view"),
    path('cohort/<int:cohort_id>/leaderboard',
         oppia_views.cohort_leaderboard_view,
         name="cohort_leaderboard"),

    path('view/',
         oppia_views.app_launch_activity_redirect_view,
         name="app_launch_activity_redirect"),
    url(r'^media/(?P<path>.*)$',
        static.serve,
        {'document_root': settings.MEDIA_ROOT}),
]

oppiamobile/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    url(r'^', include('oppia.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^content/', include('content.urls')),
    url(r'^profile/', include('profile.urls')),
    url(r'^reports/', include('reports.urls')),
    url(r'^activitylog/', include('activitylog.urls')),
    url(r'^viz/', include('viz.urls')),
    path(r'av', include('av.urls', namespace="oppia_av")),
    url(r'^gamification/', include('gamification.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^integrations/', include('integrations.urls')),
]

profile/urls.py
from django.contrib.auth import views as django_contrib_auth_views
from django.urls import path
from django.views import i18n as django_views_i18n
from django.views.generic import TemplateView

from profile import views as profile_views

app_name = 'profile'

urlpatterns = [
    path('register/', profile_views.register, name="register"),
    path('register/thanks/',
         TemplateView.as_view(template_name="oppia/thanks.html"),
         name="register_thanks"),
    path('login/', profile_views.login_view, name="login"),
    path('logout/',
         django_contrib_auth_views.LogoutView.as_view(),
         {'template_name': 'oppia/logout.html', },
         name="logout"),
    path('setlang/', django_views_i18n.set_language, name="set_language"),
    path('reset/', profile_views.reset, name="reset"),
    path('reset/sent/',
         TemplateView.as_view(template_name="profile/reset-sent.html"),
         name="reset_sent"),
    path('edit/', profile_views.edit, name="edit"),
    path('edit/<int:user_id>/', profile_views.edit, name="edit_user"),
    path('points/', profile_views.points, name="points"),
    path('badges/', profile_views.badges, name="badges"),
    path('<int:user_id>/activity/',
         profile_views.user_activity,
         name="user_activity"),
    path('<int:user_id>/<int:course_id>/activity/',
         profile_views.user_course_activity_view,
         name="user_course_activity"),

    path('<int:user_id>/quizattempts/',
         profile_views.UserAttemptsList.as_view(),
         name="user_all_attempts"),

    path('<int:user_id>/<int:course_id>/quiz/<int:quiz_id>/attempts/',
         profile_views.QuizAttemptsList.as_view(),
         name="user_quiz_attempts"),

    path('<int:user_id>/<int:course_id>/quiz/<int:quiz_id>/attempts/<int:pk>',
         profile_views.QuizAttemptDetail.as_view(),
         name="quiz_attempt_detail"),

    path('upload/', profile_views.UploadUsers.as_view(), name="upload"),
    path('search/', profile_views.search_users, name="search"),
    path('export/', profile_views.export_users, name="export"),
    path('list/', profile_views.list_users, name="list"),

    path('delete/<int:user_id>/', profile_views.delete_account_view, name="delete"),
    path('delete/complete/',
         profile_views.delete_account_complete_view,
         name="delete_complete"),
    path('export/mydata/<data_type>',
         profile_views.export_mydata_view,
         name="export_mydata"),
]

oppia/forms/cohort.py
import datetime

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div
from django import forms
from django.utils.translation import ugettext_lazy as _


class CohortHelperDiv(Div):
    template = "cohort/helper.html"


class CohortForm(forms.Form):

    STR_VALID_DATE = _(u'Please enter a valid date')
    DATE_FORMAT = "%Y-%m-%d"

    description = forms.CharField(required=True)
    teachers = forms.CharField(
        widget=forms.Textarea(),
        required=False,
        help_text=_("A comma separated list of usernames"))
    students = forms.CharField(
        widget=forms.Textarea(),
        required=False,
        help_text=_("A comma separated list of usernames"))
    start_date = forms.CharField(
        required=True,
        error_messages={'required': STR_VALID_DATE,
                        'invalid': STR_VALID_DATE})
    end_date = forms.CharField(
        required=True,
        error_messages={'required': STR_VALID_DATE,
                        'invalid': STR_VALID_DATE})
    courses = forms.CharField(
        widget=forms.Textarea(),
        required=False,
        help_text=_("A comma separated list of course codes"))

    def __init__(self, *args, **kwargs):
        super(CohortForm, self).__init__(* args, ** kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_tag = False
        self.helper.label_class = 'col-sm-3 col-md-2'
        self.helper.field_class = 'col-sm-9 col-md-10 col-lg-9'
        self.helper.layout = Layout(
                'description',
                Div('start_date', css_class='date-picker-row'),
                Div('end_date', css_class='date-picker-row'),
                Div(
                    'courses',
                    'teachers',
                    'students',
                    css_class='d-none'
                ),
            )

    def clean(self):
        cleaned_data = super(CohortForm, self).clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        DATE_FORMAT = "%Y-%m-%d"
        try:
            start_date = datetime.datetime.strptime(start_date, DATE_FORMAT)
        except (TypeError, ValueError):
            raise forms.ValidationError(_("Please enter a valid start date"))
        try:
            end_date = datetime.datetime.strptime(end_date, DATE_FORMAT)
        except (TypeError, ValueError):
            raise forms.ValidationError(_("Please enter a valid end date"))

        # check start date before end date
        if start_date > end_date:
            raise forms.ValidationError(
                _("Start date must be before the end date."))

        return cleaned_data

oppia/views/activity.py
import datetime
import json

import tablib
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.db.models import Sum
from django.db.models.functions import TruncDay, TruncMonth, TruncYear
from django.http import HttpResponse
from django.shortcuts import render

from helpers.forms.dates import DateRangeIntervalForm, DateRangeForm
from oppia.models import Points
from oppia.models import Tracker
from oppia.permissions import can_view_course_detail
from oppia.views.utils import generate_graph_data
from reports.signals import dashboard_accessed
from summary.models import CourseDailyStats


def recent_activity(request, course_id):

    course = can_view_course_detail(request, course_id)

    dashboard_accessed.send(sender=None, request=request, data=course)

    start_date = datetime.datetime.now() - datetime.timedelta(days=31)
    end_date = datetime.datetime.now()
    interval = 'days'

    if request.method == 'POST':
        form = DateRangeIntervalForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data.get("start_date")
            start_date = datetime.datetime.strptime(start_date + " 00:00:00",
                                                    "%Y-%m-%d %H:%M:%S")
            end_date = form.cleaned_data.get("end_date")
            end_date = datetime.datetime.strptime(end_date + " 23:59:59",
                                                  "%Y-%m-%d %H:%M:%S")
            interval = form.cleaned_data.get("interval")
    else:
        data = {}
        data['start_date'] = start_date
        data['end_date'] = end_date
        data['interval'] = interval
        form = DateRangeIntervalForm(initial=data)

    dates = []
    if interval == 'days':
        daily_stats = CourseDailyStats.objects.filter(course=course,
                                                      day__gte=start_date,
                                                      day__lte=end_date) \
                        .annotate(stat_date=TruncDay('day')) \
                        .values('stat_date', 'type') \
                        .annotate(total=Sum('total'))

        dates = generate_graph_data(daily_stats, False)

    else:
        monthly_stats = CourseDailyStats.objects.filter(course=course,
                                                        day__gte=start_date,
                                                        day__lte=end_date) \
                        .annotate(month=TruncMonth('day'),
                                  year=TruncYear('day')) \
                        .values('month', 'year', 'type') \
                        .annotate(total=Sum('total')) \
                        .order_by('year', 'month')

        dates = generate_graph_data(monthly_stats, True)

    leaderboard = Points.get_leaderboard(10, course)
    return render(request, 'course/activity.html',
                  {'course': course,
                   'monthly': interval == 'months',
                   'form': form,
                   'data': dates,
                   'leaderboard': leaderboard})


def recent_activity_detail(request, course_id):
    course = can_view_course_detail(request, course_id)

    start_date = datetime.datetime.now() - datetime.timedelta(days=31)
    end_date = datetime.datetime.now()
    if request.method == 'POST':
        form = DateRangeForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data.get("start_date")
            start_date = datetime.datetime.strptime(start_date, "%Y-%m-%d")
            end_date = form.cleaned_data.get("end_date")
            end_date = datetime.datetime.strptime(end_date, "%Y-%m-%d")
            trackers = Tracker.objects.filter(course=course,
                                              tracker_date__gte=start_date,
                                              tracker_date__lte=end_date) \
                              .order_by('-tracker_date')
        else:
            trackers = Tracker.objects.filter(course=course) \
                .order_by('-tracker_date')
    else:
        data = {}
        data['start_date'] = start_date
        data['end_date'] = end_date
        form = DateRangeForm(initial=data)
        trackers = Tracker.objects.filter(course=course) \
            .order_by('-tracker_date')

    paginator = Paginator(trackers, 25)
    # Make sure page request is an int. If not, deliver first page.
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    # If page request (9999) is out of range, deliver last page of results.
    try:
        tracks = paginator.page(page)
        for t in tracks:
            t.data_obj = []
            try:
                data_dict = json.loads(t.data)
                for key, value in data_dict.items():
                    t.data_obj.append([key, value])
            except ValueError:
                pass
            t.data_obj.append(['agent', t.agent])
            t.data_obj.append(['ip', t.ip])
    except (EmptyPage, InvalidPage):
        tracks = paginator.page(paginator.num_pages)

    return render(request, 'course/activity-detail.html',
                  {'course': course,
                   'form': form,
                   'page': tracks, })


def export_tracker_detail(request, course_id):
    course = can_view_course_detail(request, course_id)

    headers = ('Date',
               'UserId',
               'Type',
               'Activity Title',
               'Section Title',
               'Time Taken',
               'IP Address',
               'User Agent',
               'Language')
    data = []
    data = tablib.Dataset(* data, headers=headers)
    trackers = Tracker.objects.filter(course=course).order_by('-tracker_date')
    for t in trackers:
        try:
            data_dict = json.loads(t.data)
            if 'lang' in data_dict:
                lang = data_dict['lang']
            else:
                lang = ""
            data.append((t.tracker_date.strftime('%Y-%m-%d %H:%M:%S'),
                         t.user.id,
                         t.type,
                         t.get_activity_title(),
                         t.get_section_title(),
                         t.time_taken,
                         t.ip,
                         t.agent,
                         lang))
        except ValueError:
            data.append((t.tracker_date.strftime('%Y-%m-%d %H:%M:%S'),
                         t.user.id,
                         t.type,
                         "",
                         "",
                         t.time_taken,
                         t.ip,
                         t.agent,
                         ""))

    response = HttpResponse(
        data.export('xlsx'),
        content_type='application/vnd.ms-excel;charset=utf-8')
    response['Content-Disposition'] = "attachment; filename=export.xlsx"

    return response

templates/cohort/activity.html
{% extends "base.html" %}
{% load i18n %}
{% load display_functions %}

{% block extra_head_title %}
	{{ cohort.description }}
{% endblock extra_head_title %}

{% block header %}
<div class="jumbotron mb-4">
    <div class="row">
			<div class="col-md-10">
				<h3><a href="{% url 'oppia:cohorts' %}">{% trans 'Cohorts' %}</a> <em class="material-icons md-18 ">arrow_forward_ios</em> {{ cohort.description }}</h3>
			</div>
			<div class="col-md-2 text-right">
				<a href="{% url 'oppia:cohort_edit' cohort.id %}" class="btn btn-light mr-2">{% trans 'Edit' %}</a>
			</div>
	</div>

</div>
{% endblock header %}

{% block content %}

<h3>{% trans 'Recent Activity' %}</h3>

{% include "oppia/includes/activity-graph.html" %}	

<h3>{% trans 'Leaderboard' %}</h3>

{% include "oppia/includes/leaderboard.html" %}

<div><a href="{% url 'oppia:cohort_leaderboard' cohort.id %}">{% trans "more..." %}</a></div>

<h3>{% trans 'Courses' %}</h3>
<div class="table-responsive">
         <table class="table table-striped">
         	 <caption class="d-none">{% trans 'Courses' %}</caption>
         	 <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">{% trans 'Course' %}</th>
                </tr>
              </thead>
              <tbody>

			{% for course in cohort.get_courses %}
				<tr>
                  <td>{{ forloop.counter }}</td>
                  <td><a href="{% url 'oppia:cohort_course_view' cohort.id course.id %}">{{ course.title|title_lang:LANGUAGE_CODE }}</a></td>
                 </tr>
			{% endfor %}
			</tbody>
 		</table>
</div>
{% endblock %}

templates/cohort/course-activity.html
{% extends "base.html" %}
{% load i18n %}
{% load display_functions %}
{% load sort_link %}
{% load static %}

{% block extra_head_title %}
	{{ cohort.description }} &gt; {{ course.title|title_lang:LANGUAGE_CODE}}
{% endblock extra_head_title %}

{% block header %}
<div class="jumbotron mb-4">
	<h4><a href="{% url 'oppia:cohorts' %}">{% trans 'Cohorts' %}</a>
		<em class="material-icons md-18 ">arrow_forward_ios</em>
	<a href="{% url 'oppia:cohort_view' cohort.id %}">{{ cohort.description }}</a>
		<em class="material-icons md-18 ">arrow_forward_ios</em>
		{{ course.title|title_lang:LANGUAGE_CODE}}
	</h4>
</div>
{% endblock header %}


{% block content %}

<h3>{% trans 'Recent Activity' %}</h3>

{% include "oppia/includes/activity-graph.html" %}	


<h3>{% trans 'Students' %}</h3>

<div class="table-responsive">
         <table class="table table-striped-expandable">
         	<caption class="d-none">{% trans 'Students' %}</caption>
         	<thead>
                <tr>
                  <th scope="col">{% sort_link 'user_display' 'Student' %}</th>
                  <th scope="col">{% sort_link 'pretest_score' 'Pre-test Score' %}</th>
                  <th scope="col">{% sort_link 'no_activities_completed' 'Activities Completed' %}</th>
                  <th scope="col">{% sort_link 'no_quizzes_completed' 'Quizzes Completed' %}</th>
                  <th scope="col">{% sort_link 'no_points' 'Points' %}</th>
                  <th scope="col">{% sort_link 'no_badges' 'Badges' %}</th>
                {% if course_media_count > 0 %}
                  <th scope="col">{% sort_link 'no_media_viewed' 'Media viewed' %}</th>
                {% endif %}
                </tr>
              </thead>
             <tbody>
				{% for student in students %}
					<tr>
						<td><a href="{% url 'profile:user_course_activity' student.user.id course.id %}">{{ student.user.first_name }} {{ student.user.last_name }}</a></td>
						<td>
							{% if student.pretest_score %}
								{{ student.pretest_score }}%
							{% else %}
								--
							{% endif %}
						</td>
						<td>{{ student.no_activities_completed }}/{{ course.get_no_activities }}</td>
						<td>{{ student.no_quizzes_completed }}/{{ course.get_no_quizzes }}</td>
						<td>{{ student.no_points }}</td>
						<td>
							{% if student.no_badges > 0 %}
								<span class="badges"
									title="{% trans 'Badge' %}"><img
									src="{% static "oppia/images/badge.png" %}"
									alt="{% trans 'Badge' %}" /></span>
							{% else %}
								&nbsp;
							{% endif %}
						</td>
                        {% if course_media_count > 0 %}
                        <td>
                            {{ student.no_media_viewed }}/{{ course_media_count }}
                        </td>
                        {% endif %}
					</tr>
				{% endfor %}
			</tbody>
 		</table>
	</div>

{% endblock %}

templates/cohort/helper.html
{% load i18n %}
{% load display_functions %}

{% url 'profile:list' as users_list_url %}
{% url 'oppia:course' as courses_list_url %}

<hr>
<div class="row selectable-group">
    <div class="table-responsive col-sm-6">
    <h4>{% trans 'Selected courses' %}</h4>
         <div class="panel panel-default explanation" {% if selected_courses %} style="display:none;" {% endif %}>
             <div class="panel-heading"></div>
             <div class="panel-body">
                 <div class="text-center" >
                     <p style="font-size:1.3em;"> {% trans 'No courses selected yet.' %}</p>

                 </div>
                <div id="courses-display" class="collapse">
                    Add courses from the "Available courses" lists by clicking the button with the <em class="fas fa-plus"></em> sign.
                    If you want to remove one selected course, press the button with the <em class="fas fa-minus"></em> sign by its side.
                 </div>
             </div>
         </div>
         <table class="table selected-items-table" id="selected-courses-table" {% if not selected_courses %} style="display:none;" {% endif %} >
         	 <caption class="d-none">{% trans 'Selected courses' %}</caption>
             <thead>
                <tr>
                  <th scope="col">{% trans 'Course' %}</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody class="selected-items" id="selected-courses" style="max-height:300px;">
              {% for course in selected_courses %}
                <tr id="{{ course.shortname }}"  data-selectable-id="{{ course.shortname }}">
                    <td class="actions">
                        <a class="btn btn-sm btn-inline btn-primary btn-add" style="display: none;"><em class="fas fa-plus"></em> <em class="far fa-check-circle hidden"></em> </a>
                        <a class="btn btn-sm btn-inline btn-primary btn-remove removing" ><em class="fas fa-minus"></em> </a>
                    </td>
                    <td >{{ course.title | title_lang:LANGUAGE_CODE }}</td>
                    <td >{{ course.lastupdated_date|date:"d/m/Y" }}</td>
                </tr>
              {% endfor %}
            </tbody>
        </table>

        <div class="text-center"><a href="#courses-display" data-show="#add-courses-block" class="btn btn-primary btn-table-toggle btn-default" data-toggle="collapse">Add courses</a></div>
    </div>


     <div class="col-sm-6" id="add-courses-block" style="display:none;">
     <h4>{% trans 'Available courses' %}</h4>
         <div id="available-courses" class="available-items">
            {% include "course/list_page.html" with ajax_url=courses_list_url page=courses_page page_ordering=c_ordering %}
         </div>
    </div>
</div>

<hr>
<div class="row selectable-group">
    <div class="table-responsive col-sm-6">
    <h4>{% trans 'Selected teachers' %}</h4>
         <div class="panel panel-default explanation" {% if selected_teachers %} style="display:none;" {% endif %}>
             <div class="panel-heading"></div>
             <div class="panel-body">
                 <div class="text-center" >
                     <p style="font-size:1.3em;"> {% trans 'No teachers selected yet.' %}</p>

                 </div>
                <div id="teachers-display" class="collapse">
                    Add students from the "Available teachers" lists by clicking the button with the <em class="fas fa-plus"></em> sign.
                    If you want to remove one selected teacher, press the button with the <em class="fas fa-minus"></em> sign by its side.
                 </div>
             </div>
         </div>
         <table class="table selected-items-table" id="selected-teachers-table" {% if not selected_teachers %} style="display:none;" {% endif %}>
         	 <caption class="d-none">{% trans 'Selected teachers' %}</caption>
             <thead>
                <tr>
                  <th scope="col">{% trans 'Teacher' %}</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody class="selected-items" id="selected-teachers" style="max-height:300px;">
              {% for teacher in selected_teachers %}
                <tr id="{{ teacher.username }}" data-selectable-id="{{ teacher.username }}">
                    <td class="actions">
                        <a class="btn btn-sm btn-inline btn-primary btn-add" style="display: none;"><em class="fas fa-plus"></em> <em class="far fa-check-circle hidden"></em> </a>
                        <a class="btn btn-sm btn-inline btn-primary btn-remove removing" ><em class="fas fa-minus"></em> </a>
                    </td>
                    <td>{% if OPPIA_SHOW_GRAVATARS %} {{ teacher|gravatar:24 }} {% endif %}
                        {{ teacher.first_name }} {{ teacher.last_name }}
                    </td>
                    <td>{{ teacher.date_joined|date:"d/m/Y" }}</td>
                </tr>
              {% endfor %}
            </tbody>
        </table>

        <div class="text-center"><a href="#teachers-display" data-show="#add-teachers-block" class="btn btn-primary btn-table-toggle btn-default" data-toggle="collapse">Add teachers</a></div>
    </div>


     <div class="col-sm-6" id="add-teachers-block" style="display:none;">
     <h4>{% trans 'Available teachers' %}</h4>
         <div id="available-teachers" class="available-items">
         {% include "profile/users-paginated-list.html" with ajax_url=users_list_url %}
         </div>
    </div>
</div>

<hr>
<div class="row selectable-group">
    <div class="table-responsive col-sm-6">
    <h4>{% trans 'Selected students' %}</h4>
         <div class="panel panel-default explanation" {% if selected_students %} style="display:none;" {% endif %}>
             <div class="panel-heading"></div>
             <div class="panel-body">
                 <div class="text-center" >
                     <p style="font-size:1.3em;"> {% trans 'No students selected yet.' %}</p>

                 </div>
                <div id="students-display" class="collapse">
                    Add students from the "Available students" lists by clicking the button with the <em class="fas fa-plus"></em> sign.
                    If you want to remove one selected student, press the button with the <em class="fas fa-minus"></em> sign by its side.
                 </div>
             </div>
         </div>
         <table class="table selected-items-table" id="selected-students-table" {% if not selected_students %} style="display:none;" {% endif %}>
             <caption class="d-none">{% trans 'Selected students' %}</caption>
             <thead>
                <tr>
                  <th scope="col">{% trans 'User' %}</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody class="selected-items" id="selected-students" style="max-height:300px;">
              {% for student in selected_students %}
                <tr id="{{ student.username }}" data-selectable-id="{{ student.username }}">
                    <td class="actions">
                        <a class="btn btn-sm btn-inline btn-primary btn-add" style="display: none;"><em class="fas fa-plus"></em> <em class="far fa-check-circle hidden"></em> </a>
                        <a class="btn btn-sm btn-inline btn-primary btn-remove removing"><em class="fas fa-minus"></em> </a>
                    </td>
                    <td>{% if OPPIA_SHOW_GRAVATARS %} {{ student|gravatar:24 }} {% endif %}
                        {{ student.first_name }} {{ student.last_name }}
                    </td>
                    <td >{{ student.date_joined|date:"d/m/Y" }}</td>
                </tr>
              {% endfor %}
            </tbody>
        </table>

        <div class="text-center"><a href="#students-display" data-show="#add-students-block" class="btn btn-primary btn-table-toggle btn-default" data-toggle="collapse">Add students</a></div>
    </div>


     <div class="col-sm-6" id="add-students-block" style="display:none;">
     <h4>{% trans 'Available students' %}</h4>
         <div id="available-students" class="available-items">
         {% include "profile/users-paginated-list.html" with ajax_url=users_list_url %}
         </div>
    </div>
</div>

templates/cohort/list.html
{% extends "base.html" %}
{% load i18n %}
{% load display_functions %}

{% block extra_head_title %}
	{% trans 'Cohorts' %}
{% endblock extra_head_title %}


{% block header %}
<div class="jumbotron mb-3">
	<h3>{% trans 'Cohorts' %}</h3>
</div>
{% endblock header %}

{% block content %}

{% if cohorts %}
	<div class="table-responsive">
         <table class="table table-striped-expandable">
            <caption class="d-none">{% trans 'Cohorts' %}</caption>
         	<thead>
                <tr>
                  <th scope="col">{% trans 'Cohort' %}</th>
                  <th scope="col">{% trans 'No Teachers' %}</th>
                  <th scope="col">{% trans 'No Students' %}</th>
                  <th scope="col">{% trans 'Courses' %}</th>
                  <th scope="col">{% trans 'Options' %}</th>
                </tr>
              </thead>
              <tbody>
	{% for cohort in cohorts %}
		<tr>
			<td><a href="{% url 'oppia:cohort_view' cohort.id %}">{{ cohort.description }}</a></td>
			<td>{{ cohort.no_teacher_members }}</td>
			<td>{{ cohort.no_student_members }}</td>
			<td>
			{% for course in cohort.get_courses %}
				<a href="{% url 'oppia:cohort_course_view' cohort.id course.id %}">{{ course.title|title_lang:LANGUAGE_CODE }}</a><br/>
			{% endfor %}
			</td>
			<td class="py-1">
				<a href="{% url 'oppia:cohort_edit' cohort.id %}" data-toggle="tooltip" title="{% trans 'Edit' %}" class="btn btn-inline btn-outline-primary"><em class="fas fa-2x fa-edit"></em> </a>
			</td>	
		</tr>
	{% endfor %}
	</tbody>
 		</table>
	</div>
{% else %}
	<p>{% trans 'No cohorts' %}</p>
	
{% endif %}

<p><a href="{% url 'oppia:cohort_add' %}" class="btn btn-default btn-primary">{% trans 'Add a cohort' %}</a></p>

{% endblock %}