av/urls.py
# av/urls.py
from django.urls import path

from av import views as av_views

app_name = 'av'

urlpatterns = [
   path('', av_views.AVHome.as_view(), name="index"),
   path('view/<int:id>/', av_views.media_view, name="view"),
   path('view/set-image-default/<int:image_id>',
        av_views.set_default_image_view,
        name="set_default_image"),
   path('upload', av_views.Upload.as_view(), name="upload"),
   path('upload/success/<int:id>/',
        av_views.UploadSuccess.as_view(),
        name="upload_success"),
]

oppiamobile/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    url(r'^', include('oppia.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^content/', include('content.urls')),
    url(r'^profile/', include('profile.urls')),
    url(r'^reports/', include('reports.urls')),
    url(r'^activitylog/', include('activitylog.urls')),
    url(r'^viz/', include('viz.urls')),
    path(r'av', include('av.urls', namespace="oppia_av")),
    url(r'^gamification/', include('gamification.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^integrations/', include('integrations.urls')),
]

profile/urls.py
from django.contrib.auth import views as django_contrib_auth_views
from django.urls import path
from django.views import i18n as django_views_i18n
from django.views.generic import TemplateView

from profile import views as profile_views

app_name = 'profile'

urlpatterns = [
    path('register/', profile_views.register, name="register"),
    path('register/thanks/',
         TemplateView.as_view(template_name="oppia/thanks.html"),
         name="register_thanks"),
    path('login/', profile_views.login_view, name="login"),
    path('logout/',
         django_contrib_auth_views.LogoutView.as_view(),
         {'template_name': 'oppia/logout.html', },
         name="logout"),
    path('setlang/', django_views_i18n.set_language, name="set_language"),
    path('reset/', profile_views.reset, name="reset"),
    path('reset/sent/',
         TemplateView.as_view(template_name="profile/reset-sent.html"),
         name="reset_sent"),
    path('edit/', profile_views.edit, name="edit"),
    path('edit/<int:user_id>/', profile_views.edit, name="edit_user"),
    path('points/', profile_views.points, name="points"),
    path('badges/', profile_views.badges, name="badges"),
    path('<int:user_id>/activity/',
         profile_views.user_activity,
         name="user_activity"),
    path('<int:user_id>/<int:course_id>/activity/',
         profile_views.user_course_activity_view,
         name="user_course_activity"),

    path('<int:user_id>/quizattempts/',
         profile_views.UserAttemptsList.as_view(),
         name="user_all_attempts"),

    path('<int:user_id>/<int:course_id>/quiz/<int:quiz_id>/attempts/',
         profile_views.QuizAttemptsList.as_view(),
         name="user_quiz_attempts"),

    path('<int:user_id>/<int:course_id>/quiz/<int:quiz_id>/attempts/<int:pk>',
         profile_views.QuizAttemptDetail.as_view(),
         name="quiz_attempt_detail"),

    path('upload/', profile_views.UploadUsers.as_view(), name="upload"),
    path('search/', profile_views.search_users, name="search"),
    path('export/', profile_views.export_users, name="export"),
    path('list/', profile_views.list_users, name="list"),

    path('delete/<int:user_id>/', profile_views.delete_account_view, name="delete"),
    path('delete/complete/',
         profile_views.delete_account_complete_view,
         name="delete_complete"),
    path('export/mydata/<data_type>',
         profile_views.export_mydata_view,
         name="export_mydata"),
]

oppia/forms/upload.py
import math

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div
from django import forms
from django.conf import settings
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from settings import constants
from settings.models import SettingProperties


class UploadCourseStep1Form(forms.Form):
    course_file = forms.FileField(
                required=True,
                error_messages={'required':
                                _('Please select a file to upload')}, )

    def __init__(self, *args, **kwargs):
        super(UploadCourseStep1Form, self).__init__(* args, ** kwargs)

        max_upload = SettingProperties.get_int(constants.MAX_UPLOAD_SIZE,
                                               settings.OPPIA_MAX_UPLOAD_SIZE)
        self.fields['course_file'].help_text = \
            _('Max size %(size)d Mb') % \
            {'size': int(math.floor(max_upload / 1024 / 1024))}

        self.helper = FormHelper()
        self.helper.form_action = reverse('oppia:upload')
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout = Layout(
                'course_file',
                Div(
                   Submit('submit',
                          _(u'Upload'),
                          css_class='btn btn-default'),
                   css_class='col-lg-offset-2 col-lg-4',
                ),
            )

    def clean(self):
        cleaned_data = super(UploadCourseStep1Form, self).clean()
        file = cleaned_data.get("course_file")

        max_upload = SettingProperties.get_int(constants.MAX_UPLOAD_SIZE,
                                               settings.OPPIA_MAX_UPLOAD_SIZE)

        if file is not None and file.size > max_upload:
            size = int(math.floor(max_upload / 1024 / 1024))
            raise forms.ValidationError(_("Your file is larger than the \
                                          maximum allowed (%(size)d Mb). You \
                                          may want to check your course for \
                                          large includes, such as images etc. \
                                          ") % {'size': size, })

        if file is not None \
                and file.content_type != 'application/zip' \
                and file.content_type != 'application/x-zip-compressed':
            raise forms.ValidationError(_("You may only upload a zip file"))

        return cleaned_data


class UploadCourseStep2Form(forms.Form):
    tags = forms.CharField(
                help_text=_("A comma separated list of tags to help classify \
                            your course"),
                required=True,
                error_messages={'required':
                                _('Please enter at least one tag')})
    is_draft = forms.BooleanField(
                help_text=_("Whether this course is only a draft"),
                required=False, )

    def __init__(self, *args, **kwargs):
        super(UploadCourseStep2Form, self).__init__(* args, ** kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout = Layout(
                'tags',
                'is_draft',
                Div(
                   Submit('submit', _(u'Save'), css_class='btn btn-default'),
                   css_class='col-lg-offset-2 col-lg-4',
                ),
            )

profile/forms/upload.py
# oppia/profile/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div
from django import forms
from django.urls import reverse
from django.utils.translation import ugettext as _


class UploadProfileForm(forms.Form):
    upload_file = forms.FileField(
        required=True,
        error_messages={'required': _('Please select a file to upload')}, )

    def __init__(self, *args, **kwargs):
        super(UploadProfileForm, self).__init__(* args, ** kwargs)
        self.helper = FormHelper()
        self.helper.form_action = reverse('profile:upload')
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout = Layout(
            'upload_file',
            Div(
                Submit('submit', _(u'Upload'), css_class='btn btn-default'),
                css_class='col-lg-offset-2 col-lg-4',
            ),
        )

templates/common/ajax_wrapper.html
<div class="ajax-load" id="{{ list_id|default:'results' }}" {% if data_initial %}data-initial="{{data_initial}}" data-preservehistory="true"{% endif %}>
    <div class="results">
        {% if query_template %}
            {% include query_template %}
        {% endif %}
    </div>
    <div class="loading-spinner">
        <div class="progress-circular progress-circular-primary">
          <div class="progress-circular-wrapper">
            <div class="progress-circular-inner">
              <div class="progress-circular-left">
                <div class="progress-circular-spinner"></div>
              </div>
              <div class="progress-circular-gap"></div>
              <div class="progress-circular-right">
                <div class="progress-circular-spinner"></div>
              </div>
            </div>
          </div>
        </div>

    </div>
    <span class="sr-only">Loading...</span>
</div>

templates/common/leaderboard-rows.html
{% load i18n %}
{% load display_functions %}
{% load static %}

{% for user in page.object_list %}
	<tr>
		<td>{{ forloop.counter0|get_index:page.start_index }}</td>
		<td>{% if OPPIA_SHOW_GRAVATARS %} {{ user|gravatar:24 }} {% endif %}
		{% if request.user.is_staff %}
			<a href="{% url 'profile:user_activity' user.id %}">{{ user.first_name }} {{ user.last_name }}</a>
		{% else %}
			{{ user.first_name }} {{ user.last_name }}
		{% endif %}
		</td>
		<td><span title="{{ user.total  }} {% trans 'points' %}">
			{{ user.total }}</span></td>
		<td>{% if user.badges > 0 %} <span class="badges"
			title="{{ user.badges }} {% trans 'badges' %}"><img
				src="{% static "oppia/images/badge.png" %}"
				alt="{{ user.badges }} {% trans 'badges' %}" /> x {{ user.badges }}</span> {% endif %}
		</td>
	</tr>
{% endfor %}

templates/common/pagination.html
{% load i18n %}
{% load query_string %}

{% if page.has_previous or page.has_next %}
<nav>
  <ul class="pagination justify-content-center">
      {% if page.has_previous %}
          <li class="page-item">
          <a class="page-link" href="{{ ajax_url }}{% query_string "" "page" %}&page={{ page.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true"><em class="fas fa-chevron-left"></em></span>
          </a>
         </li>
      {% endif %}

        {% if page.has_previous %}<li class="page-item"><a class="page-link" href="{{ ajax_url }}{% query_string "" "page" %}&page=1"> 1 <span class="sr-only"> 1</span></a></li>{% endif %}
        {% if page.previous_page_number > 2 %}<li class="page-item"><span class="page-link">...</span></li> {% endif %}
        {% if page.previous_page_number > 1 %}
            <li class="page-item"><a class="page-link" href="{{ ajax_url }}{% query_string "" "page" %}&page={{ page.previous_page_number }}"> {{ page.previous_page_number }} <span class="sr-only"> {{ page.previous_page_number }}</span></a></li>
        {% endif %}
        <li class="active page-item"><a class="page-link" href="{{ ajax_url }}{% query_string "" "page" %}&page={{ page.number }}"> {{ page.number }} <span class="sr-only"> {{ page.number }}</span></a></li>
        {% if page.next_page_number != page.paginator.num_pages %}
            <li class="page-item"><a class="page-link" href="{{ ajax_url }}{% query_string "" "page" %}&page={{ page.next_page_number }}"> {{ page.next_page_number }} <span class="sr-only"> {{ page.next_page_number }}</span></a></li>
            {% with page.next_page_number|add:"1" as secondnext_page %}
                {% if secondnext_page != page.paginator.num_pages %}
                    <li class="page-item"><span class="page-link">...</span></li>
                {% endif %}
            {% endwith %}
        {% endif %}

      {% if page.has_next %}<li class="page-item"><a class="page-link" href="{{ ajax_url }}{% query_string "" "page" %}&page={{ page.paginator.num_pages }}"> {{ page.paginator.num_pages }} <span class="sr-only"> {{ page.paginator.num_pages }}</span></a></li>{% endif %}

    {% if page.has_next %}
          <li class="page-item">
          <a class="page-link" href="{{ ajax_url }}{% query_string "" "page" %}&page={{ page.next_page_number }}" aria-label="Next">
            <span aria-hidden="true"><span class="fas fa-chevron-right"></span></span>
          </a>
         </li>
      {% endif %}
  </ul>
</nav>
{% endif %}

templates/common/quiz-response-header.html
{% extends "base.html" %}
{% load i18n %}
{% load display_functions %}
{% block extra_scripts %}
<script type="text/javascript">
	$(function(){
		$('tr[name=attemptlist]').each(function(i){
			$('#detail'+$(this).attr('id')).toggle();
			$(this).click(function() {
				$('#detail'+$(this).attr('id')).toggle(700);
			});
			}
		);
	});
</script>
{% endblock extra_scripts %}

templates/common/sort-link.html
{% load query_string %}

<a
    {% if ordered_ascending or ordered_descending %}class="sorted" {% endif %}
    href="{{ ajax_url }}{% query_string "" "page,order_by" %}&order_by={% if ordered_ascending %}-{% endif %}{{ orderby }}">
    <em class="fas
    {% if ordered_ascending %}
        fa-sort-amount-down
    {% elif ordered_descending %}
        fa-sort-amount-up
    {% else %}
        fa-sort
    {% endif %}
    "></em>
{{ title }}</a>

templates/common/upload.html
{% extends "base.html" %}
{% load i18n %}
{% load display_functions %}

{% block extra_head_title %}
	{{ title }}
{% endblock extra_head_title %}

{% load crispy_forms_tags %}

{% block header %}
<div class="jumbotron mb-3">
	<h3><em class="material-icons mr-2">arrow_upward</em> {{ title }}</h3>
</div>
{% endblock header %}

{% block content %}
<div class="container">
    <div class="row">
    	<div class="col-md-11">{% include "includes/messages.html" %}</div>
    </div>
	{% crispy form %}
</div>
{% endblock %}